---
- name: general config
  hosts: routers
  tasks:
    - name: Add Banner
      ios_banner:
        banner: login
        text: |
          test desc
        state: absent

    - name: Add loopback
      ios_interface:
        name: Loopback21
        state: absent
